server:
  port: 7071

spring:
#  zipkin:
#    enabled: true
#    base-url: http://localhost:9411
#    service:
#      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27020
      username: java11user
      password: root
      database: userdb
  rabbitmq:
    host: localhost
    port: 5672
    username: java11
    password: 123

jwt:
  secretkey: ${java11secretkey}
  issuer: ${java11issuer}
  audience: ${java11audience}

rabbitmq:
  exchange-auth: auth-exchange
  register-key: register-key
  queue-register: register-queue